server:
  port: 8096

spring:
  security:
    enabled: false
  error:
    whitelabel:
      enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/chatdb
    username: chatuser
    password: chatpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jpa:
      repository:
        base-package: com.chat.storage.repository

app:
  api-key: ${API_KEY:supersecret}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    server-url: http://localhost:8096
    path: /swagger-ui.html

resilience4j.ratelimiter:
  instances:
    apiRateLimiter:
      limitForPeriod: 10        # Max requests per period
      limitRefreshPeriod: 1s    # Time window to allow the requests
      timeoutDuration: 500ms    # Timeout for the request if rate limit is reached

logging:
  level:
    root: INFO
    com.chat.storage: DEBUG
  logback:
    # If you want to customize the file appender or other settings
    file:
      name: logs/app.log
