server:
  port: 8096

spring:
  security:
    enabled: false
  error:
    whitelabel:
      enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/chatdb  # Make sure the host is correct (use "localhost" if running locally)
    username: chatuser
    password: chatpass
    driver-class-name: org.postgresql.Driver  # Add driver class name if needed
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Specify the PostgreSQL dialect here
  data:
    jpa:
      repository:
        base-package: com.chat.storage.repository  # If you have a custom base package for your repositories

app:
  api-key: ${API_KEY:supersecret}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    server-url: http://localhost:8096
    path: /swagger-ui.html
